development:
  username: 'root'
  password: '1'
  adapter: mysql2
  database: hh_development
  encoding: utf8
  reconnect: false
  pool: 5

test:
  username: 'root'
  password: '1'
  adapter: mysql2
  database: hh_test
  encoding: utf8
  timeout: 5000

production:
  username: <%= begin IO.read("/var/.dbu") rescue "" end %>
  password: <%= begin IO.read("/var/.dbp") rescue "" end %>
  adapter: mysql2
  database: hh_production
  encoding: utf8
  timeout: 5000
